import Foundation

let activities = [
    "All", "Accordion", "Acoustic Guitar", "Acting", "Archery", "Art", "Astrology", 
    "Astronomy", "Athletics", "Badminton", "Baking", "Basketball", "Beach Volleyball", 
    "Bird Watching", "Board Games", "Book", "Boxing", "Bridge", "Camping", 
    "Candle Making", "Carpentry", "Cartooning", "Chess", "Climbing", "Coding", 
    "Community Service", "Cooking", "Cosplaying", "Cycling", "Dance", "Darts", 
    "Decorating", "Design", "Diving", "DJing", "Drawing", "Drama", "Fishing", 
    "Fitness", "Flower Arrangement", "Gardening", "Gaming", "Geocaching", 
    "Golf", "Guitar", 
    "Artistic Gymnastics", "Rhythmic Gymnastics", "Trampoline Gymnastics", 
    "Acrobatic Gymnastics", "Aerobic Gymnastics", "Parkour", "Tumbling", 
    "Men's Artistic Gymnastics", "Women's Artistic Gymnastics", 
    "Hacking", "Hiking", "Horse Riding", "Hot Air Ballooning", "Ice Skating", 
    "Illustration", "Indoor Climbing", "Jogging", "Juggling", "Karate", 
    "Kayaking", "Kite Flying", "Knitting", "Lacrosse", "Laser Tag", 
    "Martial Arts", "Meditation", "Metalworking", "Model Building", 
    "Mountain Biking", "Music", "Netball", "Origami", "Paintball", 
    "Painting", "Photography", "Pilates", "Pottery", 
    "Programming", "Puzzle Solving", "Quilting", "Rafting", "Rock Climbing", 
    "Rollerblading", "Rowing", "Sailing", "Saltwater Fishing", 
    "Sculpting", "Shooting", "Shopping", "Skateboarding", "Skating", 
    "Skiing", "Skydiving", "Snorkeling", "Snowboarding", "Soccer", 
    "Softball", "Surfing", "Swimming", "Table Tennis", "Tai Chi", 
    "Tap Dancing", "Tea Ceremony", "Teaching", "Tennis", "Theater", 
    "Triathlon", "Ultimate Frisbee", "Volleyball", "Volunteering", 
    "Water Polo", "Weightlifting", "Whittling", "Wine Tasting", 
    "Woodworking", "Yoga", "Zumba", 
    "Bass Guitar", "Cello", "Clarinet", "Drum", "Flute", "Organ", 
    "Piano", "Saxophone", "Trumpet", "Violin", "Voice", "Ukulele", 
    "Banjo", "Harmonica", "Mandolin", "Oboe", "Trombone", "Tuba", 
    "Double Bass", "Electric Guitar", "Percussion", "Beatboxing", 
    "Music Production", "Sound Engineering", "Songwriting", 
    "Music Theory", "Music Composition", "Choir", "Band", "Orchestra", 
    "Solo Performance", "Instrument Repair", "Music Appreciation", 
    "Electronic Music", "Jazz Studies", "Classical Music", "Rock Music", 
    "Pop Music", "Hip Hop Dance", "Ballet", "Contemporary Dance", 
    "Tap Dance", "Ballroom Dance", "Breakdancing", "Latin Dance", 
    "Folk Dance", "Street Dance", "Traditional Dance", "Modern Dance", 
    "Dance Choreography", "Dance Fitness", "Dance Therapy", "Dance Improvisation"
].sorted()